### PR TITLE
Added Autocompletion

### PR DESCRIPTION
**Pull request by THEBOSS0369**
I have added autocompletion function in js interpreter plus change the button style made its border round.

### CODE REVIEW

**Comment by THEBOSS0369** [comment]
Hey @sumn2u ! I have added this function, also you have already added all the function needed , so i added the autocomplete function, other than this function i am also thinking of adding syntax highlighting function. I earlier thought of adding pretty function but its already implemented in the js interpreter. Other than this i don't think anything can be added like adding different themes is out of question, it doesn't need anymore styling than the present one, that's it i checked other online iinterpreter for reference but hey were pretty same, like this website web3school https://www.w3schools.com/js/

**Review by sumn2u — APPROVED** [review]
Looks good to me. In future, I suggest to commit only those file that has code changes.

**Comment by sumn2u** [comment]
@THEBOSS0369 The changes are deployed. Great work 👏

**Comment by THEBOSS0369** [comment]
> Looks good to me. In future, I suggest to commit only those file that has code changes.

Thanku sir, I will keep that in mind from next time.

**Pull request merged**
